### ISSUE TITLE
Re-enable Posts Views Tracking

### ISSUE THREAD

**Issue by SachaG** [TelescopeJS/Telescope#1541]
Whenever a user loads a post's single page route (`/posts/:_id/:slug`), this should increment the post's `viewCount` property.

### Server

- [x] Create a new `increaseViewCount` function that takes a post `_id` and increments its view count by 1. 
- [x] Create a new GraphQL mutation that calls this function.

### Client

- [x] Wrap the `PostsPage` component with the `withMutation` helper HoC (with the appropriate options). 
- [x] Call the mutation every time `PostsPage` is mounted.
- [x] Make sure the mutation can only be called once per page load even if the component re-renders.

**Comment by kauyeung253** [comment]
@SachaG, thanks for putting this together.  I'm working on this one.

**Comment by xavcz** [comment]
Hey @kauyeung253, I've pong you on Slack, but got to do this issue for a project 🙄 

Feel free to ping back here or on Slack if you want to chat about this issue, I'd love to know how you would have done and how we could maybe better the process!

Ideas:
- keep track of the `sessionId` with `Meteor.default_connection._lastSessionId` somehow
- move the `componentDidMount` logic to `PostsSingle`: the component has direct access to the router and render `PostsPage` (maybe easier customization down the line for the developers?)

**Comment by kauyeung253** [comment]
Hey @xavcz After looking into this issue I realized I was over my head.  I've been browsing the up for grabs issues and would like to jump in as soon as I can.
